database:
  connection_string: "mongodb://localhost:8888"
  customer:
    dbName: "hepsigonulden_db"
    collectionName: "customer_details"
  user:
    dbName: "hepsigonulden_db"
    collectionName: "users"
