database:
  connection_string: "mongodb://localhost:27017"
  customer:
    dbName: "hepsigonulden_db"
    collectionName: "customer_details"
  order:
    dbName: "hepsigonulden_db"
    collectionName: "order_details"


kafka:
  brokers:
    - "localhost:9092"
  topic: "order_create"
  consumer_group_name: "prepare_order_consumer_group"


