database:
  connection_string: "mongodb://localhost:8888"
  customer:
    dbName: "hepsigonulden_db"
    collectionName: "customer_details"
  order:
    dbName: "hepsigonulden_db"
    collectionName: "order_details"
