definitions:
  types.Address:
    properties:
      city:
        type: string
      customer_id:
        type: string
      id:
        type: string
      street:
        type: string
    required:
    - city
    - street
    type: object
  types.CustomerResponseModel:
    properties:
      additional_info:
        additionalProperties:
          type: string
        type: object
      addresses:
        items:
          $ref: '#/definitions/types.Address'
        type: array
      age:
        type: integer
      contact_option:
        items:
          type: string
        type: array
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        type: string
      phone_numbers:
        items:
          $ref: '#/definitions/types.PhoneNumber'
        type: array
      token:
        type: string
      username:
        type: string
    type: object
  types.PhoneNumber:
    properties:
      customer_id:
        type: string
      id:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /customers/{id}:
    get:
      description: Get customer details by ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.CustomerResponseModel'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get customer by ID
      tags:
      - customer
swagger: "2.0"
