definitions:
  types.OrderResponseModel:
    properties:
      created_at:
        type: string
      creator_user_id:
        type: string
      customer_id:
        type: string
      order_name:
        type: string
      order_total:
        type: integer
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /orders/{id}:
    get:
      description: Get order details by ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      - description: JWT token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.OrderResponseModel'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get order by ID
      tags:
      - order
swagger: "2.0"
